# Generated by Django 5.1.4 on 2025-12-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('primary_muscle', models.CharField(max_length=200)),
            ],
        ),
    ]
