# Generated by Django 5.1.4 on 2025-12-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_muscle_workout_remove_exercise_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.muscle'),
        ),
    ]
